modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "sakisaki"
version = "${version}"
displayName = "sakié…±~"
description = "Adds a toggleable crawl mode with sound."
authors = "heStudio Community"
displayURL = "https://github.com/hestudio-community/sakisaki"

[[dependencies.sakisaki]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sakisaki]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "BOTH"
